name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - run: |
          echo pwd,
          pwd,
          tree,
          ls
     - name: Use oxr463/setup-cordova
       uses: oxr463/setup-cordova@0.0.3
       with:
        exec: |
          cordova build android
