name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Use coturiv/setup-ionic
       uses: coturiv/setup-ionic@v1
       with:
         java-version: 8
     - name: Use coturiv/setup-ionic
       uses: coturiv/setup-ionic@v1
       with:
        cordova-version: 8

     - name: Build
       run: |
        cordova build android
