name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: oxr463/setup-cordova@0.0.2
     - name: Use oxr463/setup-cordova
     - run: cordova build --no-telemetry && cp "$(find . -name '*.apk')" .
